attire:
  active: Lucho enciende las luces
  user_permissions:
    can_toggle_visibility: true
  visible: true
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.70  
name: Lucho enciende las luces

inherit:
  $course: rodri042/curso-lpysd2 # (Opcional) Es para que si abre el proyecto solo le muestre un cartel de "Este ejercicio no te va a andar a menos que estés en el curso tal"
  $assets:
    extra: true
    attires:
      - La cena de Dino
      - Lucho enciende las luces
  # -----------------------------------------------------------------
  # De acá en adelante se puede poner cualquier fragmento de meta.yml
  # para complementar cualquier propiedad que no esté definida acá...
  # -----------------------------------------------------------------
  blocks:
    defaultToolbox: true

  # ⚠⚠⚠ WARNING ⚠⚠⚠
  # Tener en cuenta que Gobstones Teacher por el momento no soporta cursos.
  # Guardar un proyecto que use herencia provocará que todos los assets heredadas terminen incorporados al proyecto.
